# frozen_string_literal: true

source "https://rubygems.org"

gem "rails", "~> 7.0"
gem "sqlite3", "~> 1.4"
gem "puma", "~> 6.0"
gem "devise", "~> 4.9"

gem "tzinfo-data", platforms: %i[windows jruby]
